# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name=b'unique product number (optional)')),
                ('size', models.CharField(blank=True, choices=[(b'ALL', b'ALL')], default=((b'ALL', b'ALL'), (b'XXS', b'XXS'), (b'XS', b'XS'), (b'S', b'S'), (b'M', b'M'), (b'XL', b'XL'), (b'XXL', b'XXL'), (b'FS', b'FREESIZE')), max_length=5, null=True)),
                ('color', models.CharField(blank=True, choices=[(b'ALL', b'ALL')], default=((b'ALL', b'ALL'), (b'BGS', b'BAGS'), (b'DRS', b'DRESS'), (b'GWN', b'GOWN'), (b'SKT', b'SKIRTS'), (b'JKT', b'JACKETS'), (b'TPS', b'TOPS')), max_length=5, null=True)),
                ('brand', models.CharField(db_index=True, max_length=255)),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('value_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sku', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOccasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.ManyToManyField(blank=True, to='product.ProductOccasion'),
        ),
    ]
