# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20160813_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
