# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('product', '0006_auto_20160813_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.ShoppingCart'),
        ),
    ]
