# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0002_remove_client_sk'),
        ('product', '0007_product_shop_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[(b'CRT', b'Created'), (b'IP', b'In Progress'), (b'PP', b'Payment Pending'), (b'CMP', b'Completed'), (b'DL', b'Delivered'), (b'CAN', b'Cancelled')], db_index=True, default=b'CRT', max_length=5)),
                ('order_id', models.CharField(db_index=True, max_length=255)),
                ('sk', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('payment_mode', models.CharField(choices=[(b'COD', b'Cash On Delivery'), (b'CC', b'Credit Card'), (b'DC', b'Debit Card'), (b'NB', b'NetBanking')], db_index=True, default=b'COD', max_length=1)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(blank=True, choices=[(b'INR', b'Indian Rupee'), (b'USD', b'US Dollar')], default=b'INR', max_length=3, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_num', models.CharField(blank=True, max_length=255, null=True)),
                ('total_qty', models.CharField(blank=True, max_length=1024, null=True)),
                ('billing_user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='management.UserProfile')),
                ('shipping_user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[(b'CRT', b'Created'), (b'IP', b'In Progress'), (b'PP', b'Payment Pending'), (b'CMP', b'Completed'), (b'DL', b'Delivered'), (b'CAN', b'Cancelled')], db_index=True, default=b'CRT', max_length=5)),
                ('sub_order_id', models.CharField(db_index=True, max_length=255)),
                ('prod_qty', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='oms.Order')),
                ('prod_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
